- name: Patch system and notify
  hosts: all
  become: yes
  tasks:

    - name: Run update script
      script: update.sh
      args:
        executable: /bin/bash

    - name: Run notify script
      script: notify.sh
      args:
        executable: /bin/bash
