- name: Patch system and notify
  hosts: all
  become: yes
  tasks:

    - name: Run update script
      command: bash update.sh
      args:
        chdir: "{{ playbook_dir }}"

    - name: Run notify script
      command: bash notify.sh
      args:
        chdir: "{{ playbook_dir }}"
