- name: Patch system and notify
  hosts: all
  become: yes
  tasks:
    - name: Clone patch script repo
      git:
        repo: 'https://github.com/siru18/Ansible-Playbook.git'
        dest: /tmp/patch-scripts

    - name: Run update script
      command: sh /tmp/patch-scripts/update.sh

    - name: Run notify script
      command: bash /tmp/patch-scripts/notify.sh
