- name: Patch system and notify
  hosts: all
  become: yes
  tasks:

    - name: Run update commands
      shell: |
        apt update -y && apt upgrade -y
        echo "Patch completed on $(hostname)" > /tmp/patch_report.txt

    - name: Send mail
      shell: |
        echo "Patching done on $(hostname)" | mail -s "✅ Patch Done on $(hostname)" srinisudhan.balaji@aravind.org
